### ISSUE TITLE
[v22.03 or earlier] Webhooks and email confirmation not working

### ISSUE THREAD

**Issue by daalta** [YunoHost-Apps/bookstack_ynh#66]
Webhooks *used* to work for me, but they stopped working at some point. I'm on v22.04, but I've had this issue before then.

Before I go any deeper: Is anyone else experiencing this issue?

**Comment by daalta** [comment]
To clarify: After creating a new webhook, and selecting any events, it never seems to get called. "Last Called:" and "Last Errored:" are both "Never".

**Comment by daalta** [comment]
Aha! How about an actual error message.
```
[2022-01-30 12:30:09] production.ERROR: Webhook call to endpoint https://this.is.a.placeholder.com/ failed with status 400  
[2022-01-30 15:20:00] production.ERROR:  {"exception":"[object] (BookStack\\Exceptions\\StoppedAuthenticationException(code: 0):  at /var/www/bookstack/app/Auth/Access/LoginService.php:40)
[stacktrace]
```
Would still appreciate if someone else could check webhooks on their installation!

**Comment by daalta** [comment]
This seems to affect the sending of verification emails as well. Stack trace:
```
[2022-02-19 16:28:00] production.ERROR:  {"exception":"[object] (BookStack\\Exceptions\\StoppedAuthenticationException(code: 0):  at /var/www/bookstack/app/Auth/Access/LoginService.php:40)
[stacktrace]
#0 /var/www/bookstack/app/Auth/Access/LoginService.php(159): BookStack\\Auth\\Access\\LoginService->login()
#1 /var/www/bookstack/app/Http/Controllers/Auth/LoginController.php(151): BookStack\\Auth\\Access\\LoginService->attempt()
#2 /var/www/bookstack/app/Http/Controllers/Auth/LoginController.php(120): BookStack\\Http\\Controllers\\Auth\\LoginController->attemptLogin()
#3 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): BookStack\\Http\\Controllers\\Auth\\LoginController->login()
#4 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(45): Illuminate\\Routing\\Controller->callAction()
#5 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Routing/Route.php(262): Illuminate\\Routing\\ControllerDispatcher->dispatch()
#6 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Routing/Route.php(205): Illuminate\\Routing\\Route->runController()
#7 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Routing/Router.php(721): Illuminate\\Routing\\Route->run()
#8 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}()
#9 /var/www/bookstack/app/Http/Middleware/CheckGuard.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#10 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): BookStack\\Http\\Middleware\\CheckGuard->handle()
#11 /var/www/bookstack/app/Http/Middleware/RedirectIfAuthenticated.php(31): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#12 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): BookStack\\Http\\Middleware\\RedirectIfAuthenticated->handle()
#13 /var/www/bookstack/app/Http/Middleware/Localization.php(82): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#14 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): BookStack\\Http\\Middleware\\Localization->handle()
#15 /var/www/bookstack/app/Http/Middleware/RunThemeActions.php(26): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#16 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): BookStack\\Http\\Middleware\\RunThemeActions->handle()
#17 /var/www/bookstack/app/Http/Middleware/CheckEmailConfirmed.php(47): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#18 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): BookStack\\Http\\Middleware\\CheckEmailConfirmed->handle()
#19 /var/www/bookstack/app/Http/Middleware/PreventAuthenticatedResponseCaching.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#20 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): BookStack\\Http\\Middleware\\PreventAuthenticatedResponseCaching->handle()
#21 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(78): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#22 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\VerifyCsrfToken->handle()
#23 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#24 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle()
#25 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(121): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#26 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(64): Illuminate\\Session\\Middleware\\StartSession->handleStatefulRequest()
#27 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Session\\Middleware\\StartSession->handle()
#28 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#29 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse->handle()
#30 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(67): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#31 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Cookie\\Middleware\\EncryptCookies->handle()
#32 /var/www/bookstack/app/Http/Middleware/ApplyCspRules.php(36): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#33 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): BookStack\\Http\\Middleware\\ApplyCspRules->handle()
#34 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#35 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Routing/Router.php(723): Illuminate\\Pipeline\\Pipeline->then()
#36 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Routing/Router.php(698): Illuminate\\Routing\\Router->runRouteWithinStack()
#37 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Routing/Router.php(662): Illuminate\\Routing\\Router->runRoute()
#38 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Routing/Router.php(651): Illuminate\\Routing\\Router->dispatchToRoute()
#39 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(167): Illuminate\\Routing\\Router->dispatch()
#40 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}()
#41 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Http/Middleware/TrustProxies.php(39): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#42 /var/www/bookstack/app/Http/Middleware/TrustProxies.php(41): Illuminate\\Http\\Middleware\\TrustProxies->handle()
#43 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): BookStack\\Http\\Middleware\\TrustProxies->handle()
#44 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#45 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TrimStrings.php(40): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()
#46 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\TrimStrings->handle()
#47 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#48 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle()
#49 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/PreventRequestsDuringMaintenance.php(86): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#50 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\PreventRequestsDuringMaintenance->handle()
#51 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#52 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(142): Illuminate\\Pipeline\\Pipeline->then()
#53 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(111): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter()
#54 /var/www/bookstack/public/index.php(53): Illuminate\\Foundation\\Http\\Kernel->handle()
#55 {main}
```

**Comment by daalta** [comment]
Upgraded to 22.04.2~ynh1, no improvement.
Checked the nginx logs, no errors there...

**Comment by ericgaspar** [comment]
I am not sure to understand what is not working... what webhooks are you talking about for what purpose. The major change in bookstack as been the LDAP authentication option...

**Comment by daalta** [comment]
@ericgaspar Oh, I'm referring to BookStack's webhooks feature.

https://www.bookstackapp.com/docs/admin/email-webhooks/

This *used* to work for me at some point! Not sure why it doesn't anymore 🤔
Just wanted to check if it's working for anyone else. Do outgoing webhooks work for you?

If they do, I can close the issue as I continue investigating ✌️

**Comment by ericgaspar** [comment]
Ah ok, I am not familiar with Bookstack webhooks and never tested it. As it could be an upstream issue, it may be worth asking @ssddanbrown intake on this.

**Comment by ssddanbrown** [comment]
BookStack functionality still working fine.

Both emails and webhooks will use queues if configured to run jobs async. 
I'm not sure exactly how yunohost is set-up, but I did spot this line:
https://github.com/YunoHost-Apps/bookstack_ynh/blob/2960899fc4d91d348c90886a774f5c5f33ce137f/conf/.env.example#L86
Added a couple of [months back in this commit](https://github.com/YunoHost-Apps/bookstack_ynh/commit/caa4159f23db3b0675c027d186f64aba84a512b0).

If using an async queue option BookStack expects a queue worker process to be setup as per our docs linked above.
Without this, jobs will be added to the queue but not processed/actioned.

**Comment by daalta** [comment]
Thank you for helping, @ssddanbrown! 😊

>  but I did spot this line:
> https://github.com/YunoHost-Apps/bookstack_ynh/blob/2960899fc4d91d348c90886a774f5c5f33ce137f/conf/.env.example#L86

Yeah, I saw that too. Fortunately @ericgaspar *did* configure redis:

https://github.com/YunoHost-Apps/bookstack_ynh/blob/2960899fc4d91d348c90886a774f5c5f33ce137f/scripts/install?q=redis#L29

My redis log seems fine (and a bit empty):

https://paste.yunohost.org/ironomaguc

-------------

My next steps will be
1. Continue asking if any other `bookstack_ynh` users are experiencing issues with email confirmation or webhooks. (Though I imagine that other users would have spoken up by now)
2. Change to `QUEUE_CONNECTION=sync`
3. Enable debug mode and start digging

Sorry if I've blown this out of proportion! It might just be a simple mistake on my end.

**Comment by ssddanbrown** [comment]
> Yeah, I saw that too. Fortunately @ericgaspar did configure redis:

Sure, so jobs will be added to a redis-based queue, but is there a PHP queue worker process running [as per our docs](https://www.bookstackapp.com/docs/admin/email-webhooks/#queue-worker-process)?

I'd test out step 2 of your above steps to check things work with the sync queue.

**Comment by ericgaspar** [comment]
@ssddanbrown Thanks for looking into this issue!

I have a serious doubt about our redis helper so I have changed the setting to database `QUEUE_CONNECTION=database` and added a systemd PHP queue worker ... 

@daalta It can be tested in this branch:
```
sudo yunohost app install https://github.com/YunoHost-Apps/bookstack_ynh/tree/Queue-Worker-Process

or

sudo yunohost app upgrade bookstack -u https://github.com/YunoHost-Apps/bookstack_ynh/tree/Queue-Worker-Process --force
```

**Comment by daalta** [comment]
@ericgaspar I'm very happy to confirm that you have solved my issue!

Email confirmation now works, and so do webhooks. Great job!! 💖💖

**Comment by ericgaspar** [comment]
Ok cool. This should be available soon in the master branch.

@ssddanbrown thanks again for your help.
